### ISSUE TITLE
Minsoo, an international student who has lots of American and Chinese friends

### ISSUE THREAD

**Issue by Hoojeong** [Hoojeong/Team3#17]
As an international student studying abroad and having lots of Chinese and American friends,  
I want to get some insights about the similarities and differences between Chinese and American norms,
So that I can understand their cultural background, which is embedded in their perspectives.
 
**Definition of done**
including a webpage that displays the comparison between Chinese and American culture. 
 
- [x] I -  does not rely on another story
- [x] N - we can make visitors deepen their understanding by showing data analysis from another category. 
- [x] V - visitors can strengthen or change their beliefs by referring to the data on the website. 
- [x] E - can adjust the number of scope of the questions
- [x] S - should only take a few hours or less
- [x] T - test with other members in our group or potential user

**Tasks**
Generate a discrete page that covers the similarities and differences between China and the US ethical values and norms.
