### ISSUE TITLE
A potential job seeker

### ISSUE THREAD

**Issue by Hoojeong** [Hoojeong/Team3#19]
As a potential job seeker,  
I want to make a website that can show my basic programming skills 
So that I can include it in my LinkedIn portfolio. 

- [x] I - does not rely on another story
- [x] N - I can show my basic level skills through various other ways.  
- [x] V - It can be valuable to show that I obtain a certain level of coding to the potential interviewers. 
- [x] E - can adjust the variety or level of expertise that would be applied to the website.
- [x] S - manageable during the rest of the J-term period
- [x] T - testable with myself.
 
**Definition of done**
building a website that can contain basic professional programming skills of mine 
shows my bio properly. 

**Tasks**
Apply as many types of commands as possible
Include a discrete bio/cv webpage.
