### ISSUE TITLE
links to further information and data sources (2pt)

### ISSUE THREAD

**Issue by Hoojeong** [Hoojeong/Team3#21]
story points = 2

(Peter) As someone very interested in global affairs and spends a decent amount of time reading/researching…

I want links to further information and data sources...

So that I can explore the issues further.

**Definition of done**
There is an easy way to go to the source of the data.

- [x] I - adding additional information does not depend on other stories
- [x] N - could be a section or page with info on the World Values Survey or embedded links
- [x] V - important to show the source for credibility but also help users explore further info
- [x] E - developing a section or page is a discreet piece of work
- [x] S - if using the same styles as other pages, should not take long
- [x] T - it will be visible on the site

**Task**
Create a hyperlink to the WVS Database website where the users are able to check/download the data we use.
