### ISSUE TITLE
include topic on views of organizations and institutions (16pts)

### ISSUE THREAD

**Issue by Hoojeong** [Hoojeong/Team3#22]
story points = 16

(Peter)As a journalist/researcher in the US writing on international affairs...
(Nanyang) As a student interested in US-China...

I want evidence-based comparisons between Americans and Chinese views on government social and private organizations... 
So that I can add depth to my stories about developments in the US-China relationship.

**Definition of done**
The data includes a topic on Chinese and American views on social, government, and international issues based on documented surveys/interviews.

- [x] I - finding data and incorporating doesn't rely on other user stories
- [x] N - flexibility on what determines evidence-based and what the exact issues are
- [x] V - primary users are people interest in US-China bilateral relationship, so views on these issues will be of interest to many users
- [x] E - the discrete task of finding data on those issues
- [x] S - should take a few hours or less
- [x] T - does the site cover opinions on Chinese and American views on social, government and international issues?

**TASK**
- Include content on Chinese and American views on organizations
