### ISSUE TITLE
A group B3 that is composed of people with various interests

### ISSUE THREAD

**Issue by Hoojeong** [Hoojeong/Team3#23]
As a group that is composed of people with various interests,  
I want a site with one discrete page and dataset per group member  
So that it is less difficult to coordinate different categories that each of us is interested in.
 
**Definition of done**
Identify the field/category of interest each group member has and build a website that has at least three different web pages about each category of interest. Compare at least 30 different opinions on at least three broad topics. 

- [x] I - does not rely on another story
- [x] N - group members can discuss which category they will take care of
- [x] V - It can be valuable for each member to get a chance to analyze their field of interest.
- [x] E - can adjust the number of categories each member would take. 
- [x] S - manageable during the rest of the J-term period
- [x] T - testable with the group members

**Task**
produce at least three sub-pages that cover three topics that each of the group members is interested in. Each sub-page contains a number of charts that show some key factors in China and the US.
