### ISSUE TITLE
Chrissy, A creator who has an interest in web site design

### ISSUE THREAD

**Issue by Hoojeong** [Hoojeong/Team3#24]
As a creator who has an interest in web site design,
I want to build a website with a decent level of visualization,
So that I can learn and understand web design skills.
 
**Definition of done**
make a website that has good visualized charts and images.
 
- [x] I -  does not rely on another story
- [x] N - group members can discuss which level of decency we want to produce
- [x] V - It can be valuable for me and other members to get web designing skills.
- [x] E - can estimate the workload considering the number of charts we need to make
- [x] S - we can set the goal which should be manageable during the rest of the J-term period
- [x] T - testable with the group members and potential users.

**Tasks**
