### ISSUE TITLE
Nanyang, A Chinese national curious about global affairs but with limited English

### ISSUE THREAD

**Issue by Hoojeong** [Hoojeong/Team3#25]
As a Chinese national curious about global affairs but with limited English…
I want to be able to easily understand the content...
So that I do not need to spend time thinking about the meaning or translating.

**Definition of done**
someone with limited English that knows what they're looking for can find the specific information in less than ~1min.

- [x] I - requires information to first be selected and included in the site before we can go through and make it more accessible for people with limited English, including translations
- [x] N - could be simple English, pictures or Chinese translations
- [x] V - the majority of Chinese have limited or very little English
- [x] E - involves discreet changes/additions
- [x] S - depends on how much text is included
- [x] T - test with a Chinese user that has limited English

**Task**
