### ISSUE TITLE
Julie, as a potential job seeker

### ISSUE THREAD

**Issue by hdcameron** [Hoojeong/Team3#37]
As a job seeker, I want to include the bios of the team and a link to LinkedIn so that prospective employers know about me and can contact me.

- [x] I - does not rely on another story
- [x]  N - I can show my basic level skills through various other ways.
- [x]  V - It can be valuable to show that I obtain a certain level of coding to the potential interviewers.
- [x]  E - can adjust the variety or level of expertise that would be applied to the website.
- [x]  S - manageable during the rest of the J-term period
- [x]  T - testable with myself.

**Definition of done**
building a website that contains basic professional programming skills and 
shows my bio properly.

**Tasks**
- create an about us page
- insert LinkedIn links
